### ISSUE TITLE
🐛 Dependencies in subpath imports are not "source mapped"

### ISSUE THREAD

**Issue by fregante** [webpro-nl/knip#1210]
### Prerequisites

- [x] I'm using the latest version
- [x] I've read the relevant [documentation](https://knip.dev)
- [x] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [x] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [x] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://stackblitz.com/edit/github-wa37qqkd?file=packages%2Fshared%2Fpackage.json,packages%2Fserver%2Fpackage.json,packages%2Fserver%2Fsrc%2Findex.ts,packages%2Fclient%2Ftsconfig.json,packages%2Fserver%2Ftsconfig.json

### Reproduction access

- [x] I've made sure the reproduction is publicly accessible

### Description of the issue

The demo uses 5.62.0 so https://github.com/webpro-nl/knip/issues/1198 is still visible:

```js
Unused dependencies (1)
@monorepo/shared  packages/server/package.json:9:6
Unresolved imports (1)
#root  packages/server/src/index.ts:1:9
```

This issue is about the unresolved import.

### Workaround

1. Install the latest via `npm i https://pkg.pr.new/knip@feb0f1b` and the first issue is resolved:

```js
Unresolved imports (1)
#root  packages/server/src/index.ts:1:9
```

2. Run `npm run build` _before_ `npm run knip`, and we're done:

```js
✂️  Excellent, Knip found no issues.
```

**Comment by webpro** [comment]
In your source code there is the `#root` specifier for which the target won't be resolved by a module resolver. If there's no "dist" file there's no mapping. 

This is a different context compared to where Knip reads `package.json#exports` to find entry points. There, we have the target "dist" specifier and can then also try to map it back to the source file.

This RFC would require a manual resolution. Perhaps best be dealt with in a new module resolver that does all the things efficiently.

In any case, I'll try to document better what is (not) supported, why, and how it can be dealt with.

**Comment by fregante** [comment]
I'm not sure I follow. It seems to me that the references in that object are resolved by Node the same way regular imports are (putting globs aside). 

I don't see why they should be treated any differently here since Node does not. These two import statements are equivalent:

```js
// index.js
import "foo";
import "#root";
``` 
```js
// package.json
{
  "imports": {
    "#root": "foo"
  }
}
```

**Comment by webpro** [comment]
>  If the import statement is resolvable

The target file isn't there (pre-build), so it isn't resolvable.

**Comment by fregante** [comment]
> so it isn't resolvable.

Yes it is. I can show you two ways:

1. Open the raw monorepo repro: https://stackblitz.com/github/webpro-nl/knip/tree/main/templates/issue-reproduction/monorepo
2. Delete `shared/src/index.ts`
3. `✂️  Excellent, Knip found no issues.`

Why can it "resolve" `@monorepo/shared` even if its entry point doesn't exist?

Other way:

1. Open the raw monorepo repro: https://stackblitz.com/github/webpro-nl/knip/tree/main/templates/issue-reproduction/monorepo?file=packages%2Fshared%2Fpackage.json
2. Change `@monorepo/shared`'s `main` field from `src/index.ts` to `dist/foo.js`
3. Rename the `shared/src/index.ts` file to `foo.ts`
4. `✂️  Excellent, Knip found no issues.`

So knip can resolve `@monorepo/shared`:

- if its entry point doesn't exist (index.js only?)
- if its entry point doesn't exist _yet_ (source mapping)

Again the way I see it is that if `import "@monorepo/shared"` is resolvable by knip, then `"imports": {"#root": "@monorepo/shared"}` should be too.


(thanks for entertaining my many RFCs/reports, by the way 🙏 )

**Comment by webpro** [comment]
>  It seems to me that the references in that object are resolved by Node the same way regular imports are (putting globs aside).

With "resolve" here we're talking about module resolution: using the import specifier in the containing file to find the target file on disk. No module resolver will succeed for a file that's not actually on disk (without hacks or special configuration).

Node (or any module resolver) does not resolve to a file if it can't find anything according to its rules (`ERR_MODULE_NOT_FOUND`). Knip internally uses both oxc-resolver and the TS module resolver and some additional logic when it comes to resolving modules from within source files. 

If we could agree on this then we might discuss further, which brings me to https://github.com/webpro-nl/knip/issues/1210#issuecomment-3170711613.

**Comment by fregante** [comment]
Ok so I seem to understand that you're internally mapping `import "foo"` to "dependency: foo" whereas in order to find what `import "#foo"` means, you're relying on an external resolver, which does goes through "#foo" and directly into an unresolved dependency. 

If so, that makes sense. This would also explain why knip can "resolve" everything in my 2 examples above.

**Comment by webpro** [comment]
Essentially for both internal and external imports we're relying on the (custom) module resolver.

This requires for the files to be on disk (does not matter if there's `package.json#exports` or `package.json#exports` involved). Only resolved files that are in `dist` can then be mapped to `src`.

Imports not found by the module resolver are marked as unresolved.

- If it looks like a package name (starts with `@` or `a-z`) it's marked as an external dependency (which could be an internal workspace)
- Otherwise it stays marked as unresolved (if it's not git-ignored)

Something that Knip does to overcome limitations, is to grab `package.json#exports` items and source-map `dist` files to `src` files and add them as entry files to be fed to the module resolver (before all of the above happens). See #853.

All of this isn't that pretty, and as I mentioned what _could_ be done here is some manual resolution after the fact for subpath imports (or ideally, create a module resolver that's not built with runtime or bundling in mind but instead optimized for static analysis/source files (and e.g. handles globs for internal resolution and multiple target files for a single specifier)).

The fix for #1198 has no resolution, it just assumes the target is an external dependency if it does not start with a dot. And I have yet to see a subpath import that is not a source file (i.e. requires a build/compile step) in the wild. But since you've opened this PR I'm assuming it is a thing.

**Comment by webpro** [comment]
Closing this issue as part of a general cleanup to keep this project sustainable and optimize my time working on it. If you think this is inappropriate or if there is no workaround and you feel stuck, feel free to [open a new issue](./new/choose). Thanks for your understanding.
